### ISSUE TITLE
May be some minor suggestions

### ISSUE THREAD

**Issue by HenryHZY** [BradyFU/Awesome-Multimodal-Large-Language-Models#1]
Hi, [Awesome-Multimodal-Large-Language-Models](https://github.com/BradyFU/Awesome-Multimodal-Large-Language-Models) is a nice repo with a great hierarchical structure. Below are some suggestions that might be helpful.

Some references are crucial but neglected in the research track of [Awesome-Multimodal-Large-Language-Models](https://github.com/BradyFU/Awesome-Multimodal-Large-Language-Models), such as VL-T5, FrozenBILM, VL-Adapter and LST. Also feel free to diff and complete the current repo with my [research trends](https://github.com/HenryHZY/Awesome-Multimodal-LLM). 

For the survey, there exists another concern that needs careful consideration: Is it worthwhile for our research community to follow tool-oriented technical reports? Although it may be difficult to determine until the result of the next top conference, I believe you could handle this matter properly. 

By the way, is there any way to participate in the ongoing MLLM survey? Thank you very much for your time.

**Comment by BradyFU** [comment]
Thanks for your constructive suggestions! We are further refining our paper list. With respect to the survey, our starting point is to help researchers quickly follow the development of MLLM, which shows great potential. Welcome to join our discussion about the survey by using the QR code on the homepage : )
