### ISSUE TITLE
Landmark Images Download Not Working Properly

### ISSUE THREAD

**Issue by chancharikmitra** [BradyFU/Awesome-Multimodal-Large-Language-Models#100]
Hi! I have recently downloaded your dataset, and I am trying to set it up properly. I understand for the landmark dataset we need to run the Python script to get 200 images from `landmark200.csv`. 

When downloading the images, only about 45-50 are properly downloading. The other links fail to download from the URL. Is it possible that there is an updated `landmark200.csv`?

**Comment by BradyFU** [comment]
We are now checking. Please wait a  moment.

**Comment by BradyFU** [comment]
Hi! We have checked the csv links. Only "03d5e3bfc958be38.jpg" can not be downloaded, and the readme file “landmark/images/readme.txt” has mentioned it and has given a solution. Please check the file and you may need to chage a network to download other images. Thank you!

**Comment by chancharikmitra** [comment]
You are correct. It seems it was a server issue. Also, I believe the download link is now actually: https://upload.wikimedia.org/wikipedia/commons/2/2a/Museo_nazionale_ferroviario_di_Pietrarsa_-_locomotiva_899.006.jpg

Perhaps, you might want to update the README. I think the issue has been resolved. Thank you!
