### ISSUE TITLE
Please add CogVLM and CogAgent to the evaluation boards

### ISSUE THREAD

**Issue by Subarasheese** [BradyFU/Awesome-Multimodal-Large-Language-Models#103]
CogVLM and CogAgent are arguably the best open vision models and are not present in the evalution boards... Can you guys evaluate them?

**Comment by BradyFU** [comment]
Now, considering the credibility of MME, our first choice is the real-name submission results of the authors themselves. We are contacting the authors of CogVLM and CogAgent for this purpose. Of course, we also encourage the community to submit their own evaluation results of CogVLM and CogAgent, and you are welcome to submit your results. : )
