### ISSUE TITLE
About LAMM git

### ISSUE THREAD

**Issue by amandajshao** [BradyFU/Awesome-Multimodal-Large-Language-Models#11]
Hi, this is the author of LAMM. We have released data, benchmark and model of LAMM. Please update the link in your list. Thank you for your support :)

Github: https://github.com/OpenLAMM/LAMM

**Comment by xjtupanda** [comment]
Thanks for sharing the great work! I've updated the corresponding items. 
btw, a small suggestion: I suppose it might be better to clarify the correlations between the benchmark and the evaluation in ["Inference"](https://github.com/OpenLAMM/LAMM#inference) part of your repo so users can get a clearer view of how to evaluate on the benchmark.

**Comment by amandajshao** [comment]
Sure. No problem. Thanks for your suggestion. We will update it asap.
