### ISSUE TITLE
OpenGVLab/InternVL

### ISSUE THREAD

**Issue by chigkim** [BradyFU/Awesome-Multimodal-Large-Language-Models#110]
Here are some more new vision-language models. Can they be added to the leaderboard?

CogAgent: https://github.com/THUDM/CogVLM
InternVL: https://github.com/OpenGVLab/InternVL
YI-VL: https://github.com/01-ai/Yi/tree/main/VL

**Comment by xjtupanda** [comment]
Thanks for your reminder. These works have been added to the repo.
