### ISSUE TITLE
Request to add InternVL-Chat-V1.1 into the MME benchmark

### ISSUE THREAD

**Issue by czczup** [BradyFU/Awesome-Multimodal-Large-Language-Models#111]
Hi,

Thanks for the efforts in building the MME benchmark!

I request to add our [InternVL-Chat-V1.1](https://github.com/OpenGVLab/InternVL/tree/main/internvl_chat#-evaluation-chinese-models) to the MME benchmark.

Title: "InternVL: Scaling up Vision Foundation Models and Aligning for Generic Visual-Linguistic Tasks"
Paper: https://arxiv.org/abs/2312.14238
Code: https://github.com/OpenGVLab/InternVL/
Evaluation Codes: https://github.com/OpenGVLab/InternVL/tree/main/internvl_chat
Results:
<img width="422" alt="image" src="https://github.com/BradyFU/Awesome-Multimodal-Large-Language-Models/assets/23737120/035eb450-f13b-49d6-8ba1-f182d84c3575">

Thank you very much!

**Comment by BradyFU** [comment]
Hi, could you send me your WeChat ID to the email bradyfu24@gmail.com? We can make further communication.
