### ISSUE TITLE
Request to add MoE-LLaVA into the repo 

### ISSUE THREAD

**Issue by LinB203** [BradyFU/Awesome-Multimodal-Large-Language-Models#113]
Hi, Thanks for the great repo!
Would you consider including our recent MoE-LLaVA into the project?

Title: "MoE-LLaVA: Mixture-of-Experts for Large Vision-Language Models"
Paper: https://arxiv.org/abs/2401.15947
Code: https://github.com/PKU-YuanGroup/MoE-LLaVA
Demo: https://huggingface.co/spaces/LanguageBind/MoE-LLaVA
Date: 2024-01-27

Great many thanks!

**Comment by BradyFU** [comment]
Hi bin, could you send me your WeChat ID via email bradyfu24@gmail.com? We can make further communication.
