### ISSUE TITLE
Request to add MoE-LLaVA-2.7B×4 into the MME benchmark

### ISSUE THREAD

**Issue by LinB203** [BradyFU/Awesome-Multimodal-Large-Language-Models#116]
Hi,

Thanks for the efforts in building the MME benchmark!

I request to add our MoE-LLaVA-2.7B×4 to the MME benchmark.

Title: "MoE-LLaVA: Mixture of Experts for Large Vision-Language Models"
Paper: https://arxiv.org/abs/2401.15947
Code: https://github.com/PKU-YuanGroup/MoE-LLaVA
Evaluation Codes: https://github.com/PKU-YuanGroup/MoE-LLaVA/blob/main/moellava/eval/model_vqa_loader.py
Results:
![1706973470621](https://github.com/BradyFU/Awesome-Multimodal-Large-Language-Models/assets/62638829/acea22e7-cb0f-4f64-b2d1-e7577948de08)

Thank you very much!

**Comment by BradyFU** [comment]
Copy that! dear binbin : )
