### ISSUE TITLE
A multimodal dataset

### ISSUE THREAD

**Issue by matrix-alpha** [BradyFU/Awesome-Multimodal-Large-Language-Models#12]
Thanks for the curated list of multimodal LLM. We have a related work that we hope is added to this awesome repository.

Accountable Textual-Visual Chat Learns to Reject Human Instructions in Image Re-creation (https://arxiv.org/pdf/2303.05983.pdf)

Project Page: https://matrix-alpha.github.io/

**Comment by xjtupanda** [comment]
Thanks for sharing! We've updated the corresponding items.

**Comment by matrix-alpha** [comment]
Thanks for your help.
