### ISSUE TITLE
What are expected to submit for the leaderboard integration?

### ISSUE THREAD

**Issue by zhimin-z** [BradyFU/Awesome-Multimodal-Large-Language-Models#124]
![image](https://github.com/BradyFU/Awesome-Multimodal-Large-Language-Models/assets/8592144/fbe9f5db-ba59-4eb3-98ec-fb9ba7a5a58e)

**Comment by BradyFU** [comment]
Hi Zhimin, you could send your WeChat ID to the email for further contact. Thanks!

**Comment by zhimin-z** [comment]
> Hi Zhimin, you could send your WeChat ID to the email for further contact. Thanks!

Mine is knighty_nine, would you contact further on this?
