### ISSUE TITLE
Add `MetaTransformer`

### ISSUE THREAD

**Issue by JustinDoIt** [BradyFU/Awesome-Multimodal-Large-Language-Models#125]
Hi, thanks for nice work. 

I want to ask why there is no Meta-Transformer: A Unified Framework for Multimodal Learning [[arXiv:2307.10802](https://arxiv.org/abs/2307.10802)], which has got 1.4k star in github  [[github.com/invictus717/MetaTransformer](https://github.com/invictus717/MetaTransformer)]? For some reasons?

**Comment by BradyFU** [comment]
Thanks for your suggestion. MetaTransformer is an excellent work. For our repo, it would be much better to include a large language model.
