### ISSUE TITLE
Related Work

### ISSUE THREAD

**Issue by YunxinLi** [BradyFU/Awesome-Multimodal-Large-Language-Models#13]
Such exciting project list of multimodal LLM. We have a related work that we hope is added to this awesome repository.

Paper Title: LMEye: An Interactive Perception Network for Large Language Models

Project:  https://github.com/YunxinLi/LingCloud

**Comment by xjtupanda** [comment]
Thanks for sharing your work! The corresponding items have been updated. I suggest that you should give the instruction-following dataset a more concise name if you don't mind.
