### ISSUE TITLE
GPT4V evaluation prompt

### ISSUE THREAD

**Issue by LengSicong** [BradyFU/Awesome-Multimodal-Large-Language-Models#131]
Hi authors,

Congrats on this great work! However, the results we have reproduced from GPT4V are quite different from those reported in the leaderboard. May I ask you to kindly provide the prompt that you are using to evaluate GPT4V?

**Comment by BradyFU** [comment]
Hi Sicong, thanks for your attention. We only use the same prompt in the MME. GPT4V has many versions on different times.
