### ISSUE TITLE
Could also include LLaVA-NeXT

### ISSUE THREAD

**Issue by nishgop** [BradyFU/Awesome-Multimodal-Large-Language-Models#138]
This is great work! Could you also include[ LLaVA-NeXT](https://llava-vl.github.io/blog/2024-01-30-llava-next/) and also Claude 3 (Opus, Sonnet & Haiku)? LLaVA-NeXT (open) was announced on Jan 31st and Anthropic's Claude 3 Series (closed) the first week of March and including these should make your content up-to-date.

**Comment by xjtupanda** [comment]
Thanks for your reminder! We've made corresponding updates.
