### ISSUE TITLE
a recent work about MLLM evaluation

### ISSUE THREAD

**Issue by IsakZhang** [BradyFU/Awesome-Multimodal-Large-Language-Models#14]
Hi, thanks for curating this awesome list! There is a recent paper that evaluates several MLLM (InstructBLIP, BLIP2 etc) on more challenging human exam questions requiring images:

M3Exam: A Multilingual, Multimodal, Multilevel Benchmark for Examining Large Language Models 
arXiv: https://arxiv.org/pdf/2306.05179.pdf
Github: https://github.com/DAMO-NLP-SG/M3Exam

Maybe you can consider adding this since it quite relates to this repo. Thanks!

**Comment by xjtupanda** [comment]
Thanks for sharing! We've updated our repo.
