### ISSUE TITLE
Plese update the content

### ISSUE THREAD

**Issue by SetoKaiba** [BradyFU/Awesome-Multimodal-Large-Language-Models#140]
https://github.com/baaivision/Emu

Only the paper of Emu1 is listed. I think the Em2 paper should be listed as well.
And the repo should refer to Emu1 and Emu2 directly.
https://github.com/BradyFU/Awesome-Multimodal-Large-Language-Models/blob/main/README.md?plain=1#L251
https://github.com/BradyFU/Awesome-Multimodal-Large-Language-Models/blob/main/README.md?plain=1#L334

https://github.com/LLaVA-VL/LLaVA-Plus-Codebase

LLaVA-Plus code is released, but it's still listed as coming soon.
https://github.com/BradyFU/Awesome-Multimodal-Large-Language-Models/blob/main/README.md?plain=1#L164

**Comment by xjtupanda** [comment]
Thanks for your reminder! We've updated the repo accordingly.
