### ISSUE TITLE
 Request to add new project

### ISSUE THREAD

**Issue by zzhanghub** [BradyFU/Awesome-Multimodal-Large-Language-Models#146]
A very interesting deep application case of MLLM: Graphic Design Large Model - Graphist. Could it be added to this list? 🤔

Paper: https://arxiv.org/abs/2404.14368
Repo: https://github.com/graphic-design-ai/graphist

**Comment by xjtupanda** [comment]
Thanks for sharing. Your work has been added to the repo.
