### ISSUE TITLE
Related work

### ISSUE THREAD

**Issue by chenjoya** [BradyFU/Awesome-Multimodal-Large-Language-Models#15]
Thanks for the amazing survey. We have a related work and hope you could consider to include.

AssistGPT: A General Multi-modal Assistant that can Plan, Execute, Inspect, and Learn (https://arxiv.org/abs/2306.08640)

Project Page: https://assistgpt-project.github.io/

**Comment by BradyFU** [comment]
Thanks for your reminder. The good work has been included to our list.
