### ISSUE TITLE
Image in landmark download error

### ISSUE THREAD

**Issue by berry-ding** [BradyFU/Awesome-Multimodal-Large-Language-Models#151]
Great work! In landmark benchmark, I found that the image_id '03d5e3bfc958be38' and download link 'https://upload.wikimedia.org/wikipedia/commons/a/a2/Pietrarsa_railway_museum_67.JPG' return a 'File not found' Error. Any suggestion to solve it ?

**Comment by BradyFU** [comment]
Hi, thanks! Please see the readme file in landmark/images/readme.txt:

On June 29, 2023, we find that the link of "03d5e3bfc958be38.jpg" may no longer work, you may consider downloading it from the link below as a replacement, following its license:

Link: https://www.wikidata.org/wiki/Q310249#/media/File:Museo_nazionale_ferroviario_di_Pietrarsa_-_locomotiva_899.006.jpg
