### ISSUE TITLE
Inquiry for including Online Demo

### ISSUE THREAD

**Issue by ByungKwanLee** [BradyFU/Awesome-Multimodal-Large-Language-Models#153]
Hi I am an author of the paper "Meteor: Mamba-based traversal of rationale for Large Language and Vision Models"

Recently, I added the online demo by Gradio in huggingface space

Then, I would like to inquire you to replace the "Local Demo" with the online demo link https://huggingface.co/spaces/BK-Lee/Meteor

Thanks in advance!

**Comment by xjtupanda** [comment]
Thanks for your reminder. That part has been updated. 
Please also consider citing our survey paper:
```
@article{yin2023survey,
  title={A Survey on Multimodal Large Language Models},
  author={Yin, Shukang and Fu, Chaoyou and Zhao, Sirui and Li, Ke and Sun, Xing and Xu, Tong and Chen, Enhong},
  journal={arXiv preprint arXiv:2306.13549},
  year={2023}
}
```
