### ISSUE TITLE
Add CharXiv

### ISSUE THREAD

**Issue by zwcolin** [BradyFU/Awesome-Multimodal-Large-Language-Models#173]
Thanks for the awesome compilation of MLLM related works! We recently released a chart understanding benchmark CharXiv with evaluations on 40+ models and it would be great if it can be included in your repo. Thanks!

project page: [charxiv.github.io](https://charxiv.github.io/)

**Comment by xjtupanda** [comment]
Thanks for sharing! We've added the project to our repo.

**Comment by zwcolin** [comment]
Thank you! we appreciate your help :)

**Comment by zwcolin** [comment]
If it's possible, could you also add it under https://github.com/BradyFU/Awesome-Multimodal-Large-Language-Models?tab=readme-ov-file#evaluation? We had a lot of model analysis inside the paper and we would appreciate if it can also be listed there like other papers. Thank you in advance!

**Comment by xjtupanda** [comment]
Sure. It's included in the Evaluation section now.
