### ISSUE TITLE
A Question about Evaluation with V100

### ISSUE THREAD

**Issue by rovgtjktm66** [BradyFU/Awesome-Multimodal-Large-Language-Models#18]
Hi, thanks for the great work! BLIP-2's FlanT5-xxl use bfloat16, while V100 does not support bfloat16. As shown in your paper, all your experiments are done using V100 GPU. I also use V100 in my lab. Are there any methods to run BLIP-2 FlanT5 on the V100 GPU?

**Comment by BradyFU** [comment]
Thanks for your interest in our work. There is no problem when just performing inference on the V100 GPU.
