### ISSUE TITLE
Experiment Results

### ISSUE THREAD

**Issue by luckysheep861** [BradyFU/Awesome-Multimodal-Large-Language-Models#23]
I wanna know why so many models achieve scores lower than 75 in Fig 2, but the random accuracies of the two metrics are equal to 50% and 25%. Didnt they follow the instruction? Didnt they answer yes/no?

**Comment by BradyFU** [comment]
Thanks for your interest in our work. The challenges faced by each model are not consistent, but include these: (1) the tasks (especially cognitive ones) are beyond the ability (perception and reasoning) of the current model; (2) do not follow instructions; (3) object hallucination following instructions (always answer "yes").
