### ISSUE TITLE
Load images to evaluate our model.

### ISSUE THREAD

**Issue by Luodian** [BradyFU/Awesome-Multimodal-Large-Language-Models#25]
May I know where could I load the images such as `tt0074749.jpg` to evaluate our model? I can see some of them are COCO format but some are not. What could I do if I wish to submit our own result?

**Comment by Luodian** [comment]
Thanks! I've found the email at README and sent an email for accessing the dataset~

**Comment by BradyFU** [comment]
Thanks : )
