### ISSUE TITLE
Related works

### ISSUE THREAD

**Issue by zeroQiaoba** [BradyFU/Awesome-Multimodal-Large-Language-Models#26]
We have a related work that we hope is added to this awesome repository. Thanks a lot.

Paper Title: Explainable Multimodal Emotion Reasoning

Paper link: https://arxiv.org/pdf/2306.15401.pdf

Project: https://github.com/zeroQiaoba/Explainable-Multimodal-Emotion-Reasoning

**Comment by BradyFU** [comment]
Thanks! The paper and project have been updated.
