### ISSUE TITLE
evaluate llava-13B base on vicuna-13B v1.1

### ISSUE THREAD

**Issue by aprilehannibal** [BradyFU/Awesome-Multimodal-Large-Language-Models#28]
Great work! Can you evaluate llava-13B base on vicuna-13B v1.1? Thanks!

**Comment by BradyFU** [comment]
Thanks for your attention and suggestion! Due to resource constraints, we recommend that you can apply for MME and evaluate the model by our provided eval tool. If there are results, welcome to let us know, thank you very much : )
