### ISSUE TITLE
May I ask if poster refers to a  placard like this？

### ISSUE THREAD

**Issue by hangzeli08** [BradyFU/Awesome-Multimodal-Large-Language-Models#30]
<img width="330" alt="image" src="https://github.com/BradyFU/Awesome-Multimodal-Large-Language-Models/assets/104003969/b2962be5-bae8-4175-ab4a-0cfefb097281">
<img width="309" alt="image" src="https://github.com/BradyFU/Awesome-Multimodal-Large-Language-Models/assets/104003969/7b33f4eb-c0c4-4a7b-8d82-0bf65999fd57">
<img width="464" alt="image" src="https://github.com/BradyFU/Awesome-Multimodal-Large-Language-Models/assets/104003969/fd2979f2-9f52-4b1d-a56c-f56f7526d5bf">
<img width="464" alt="image" src="https://github.com/BradyFU/Awesome-Multimodal-Large-Language-Models/assets/104003969/10ff64c8-4eac-4c1f-86ff-4c2cc1447b0f">
A poster like this？or something else？

**Comment by BradyFU** [comment]
Thanks. The poster in MME refers to the movie poster.

**Comment by hangzeli08** [comment]
请问指的是海报内容理解还是AI海报制作还是？

**Comment by hangzeli08** [comment]
Do you mean understanding the content of the poster or AI poster production?

**Comment by hangzeli08** [comment]
thank you～

**Comment by BradyFU** [comment]
Thank you too : )
