### ISSUE TITLE
Demo of Polite Flamingo and PF-1M dataset are ready

### ISSUE THREAD

**Issue by ChenDelong1999** [BradyFU/Awesome-Multimodal-Large-Language-Models#32]
Thanks for this awesome repo!

Our work (Polite Flamingo) has some updated links.

Demo link: http://clever_flamingo.xiaoice.com/
Dataset link: https://huggingface.co/datasets/chendelong/PF-1M/tree/main

Suggesting to modifiy the dataset note of PF-1M into:
```
A collection of 37 vision-language dataset with responses rewriten by Polite Flamingo.
```

Thanks a lot~

**Comment by BradyFU** [comment]
Many thanks! We have updated : )
