### ISSUE TITLE
Include LENS

### ISSUE THREAD

**Issue by detaos** [BradyFU/Awesome-Multimodal-Large-Language-Models#35]
https://arxiv.org/abs/2306.16410

We propose LENS, a modular approach for tackling computer vision problems by leveraging the power of large language models (LLMs). Our system uses a language model to reason over outputs from a set of independent and highly descriptive vision modules that provide exhaustive information about an image. We evaluate the approach on pure computer vision settings such as zero- and few-shot object recognition, as well as on vision and language problems. LENS can be applied to any off-the-shelf LLM and we find that the LLMs with LENS perform highly competitively with much bigger and much more sophisticated systems, without any multimodal training whatsoever. We open-source our code at [this https URL](https://github.com/ContextualAI/lens) and provide an interactive demo.

**Comment by xjtupanda** [comment]
Thanks for sharing! We've included your work.
