### ISSUE TITLE
mPLUG-DocOwl

### ISSUE THREAD

**Issue by MAGAer13** [BradyFU/Awesome-Multimodal-Large-Language-Models#38]
https://arxiv.org/abs/2307.02499

we propose mPLUG-DocOwl based on mPLUG-Owl for OCR-free document understanding. Specifically, we first construct a instruction tuning dataset featuring a wide range of visual-text understanding tasks. Then, we strengthen the OCR-free document understanding ability by jointly train the model on language-only, general vision-and-language, and document instruction tuning dataset with our unified instruction tuning strategy. We also build an OCR-free document instruction understanding evaluation set LLMDoc to better compare models' capabilities on instruct compliance and document understanding. Experimental results show that our model outperforms existing multi-modal models, demonstrating its strong ability of document understanding. Besides, without specific fine-tuning, mPLUG-DocOwl generalizes well on various downstream tasks. We open-source our code at [this https URL](https://github.com/X-PLUG/mPLUG-DocOwl) and provide an interactive demo.

**Comment by xjtupanda** [comment]
Thanks for sharing! We've included it in the repo.
