### ISSUE TITLE
A new ICCV 2023 paper about Multimodal In-context Learning - ICL-D3IE

### ISSUE THREAD

**Issue by demoleiwang** [BradyFU/Awesome-Multimodal-Large-Language-Models#39]
Hi,

We have a new accepted paper, which might be related to mm in-context learning and LLM-aided visual reasoning. 
[ICL-D3IE: In-context learning with diverse demonstrations updating for document information extraction](https://arxiv.org/abs/2303.05063) 

Thanks!

**Comment by xjtupanda** [comment]
Thanks for sharing! We've included it in our repo.
