### ISSUE TITLE
Update the github link of ICL-D3IE in Readme

### ISSUE THREAD

**Issue by MAEHCM** [BradyFU/Awesome-Multimodal-Large-Language-Models#41]
The GitHub link to ICL-D3IE is now accessible. If possible, could you add it to the readme?
Furthermore, we have a new paper about Multimodal Chain-of-Thought. Would it be possible to add this paper to your paper list? The paper's name is T-SciQ: Teaching Multimodal Chain-of-Thought Reasoning via Large Language Model Signals for Science Question Answering. (https://arxiv.org/abs/2305.03453)

Thank you.

**Comment by xjtupanda** [comment]
Thanks for your reminder! We've updated the link and added the paper.
