### ISSUE TITLE
Inference prompt for MME evaluation

### ISSUE THREAD

**Issue by khanrc** [BradyFU/Awesome-Multimodal-Large-Language-Models#44]
Hello, I first would like to say thank you for this great repository.

I evaluated mPLUG-Owl using their official prompt as following:

```
The following is a conversation between a curious human and AI assistant. The assistant gives helpful, detailed, and polite answers to the user's questions.
Human: <image>
Human: {question}
AI: 
```

But I got score of about 1100, which is worse than the reported number in the MME paper (about 1250).

What is the exact prompt you used for evaluatation?

**Comment by BradyFU** [comment]
Thanks! We also use their official settings.

**Comment by khanrc** [comment]
Thank you for your quick response.
Would you be able to share your inference code? We got MME score around 1100, but we couldn't find any bugs in the code.

**Comment by BradyFU** [comment]
Would you mind leave your WeChat ID? We can communicate further through WeChat.
