### ISSUE TITLE
Inconsistent Results for Mini-GPT4 with Vicuna-13b

### ISSUE THREAD

**Issue by zycheiheihei** [BradyFU/Awesome-Multimodal-Large-Language-Models#50]
I re-evaluate the performance of Mini-GPT4 with Vicuna-13B on MME, using the [MMBench](https://opencompass.org.cn/MMBench) code base. I got scores of 580.5 for perception and 144.29 for cognition, which are very close to the result in the official [leaderboard](https://github.com/BradyFU/Awesome-Multimodal-Large-Language-Models/blob/Evaluation/README.md). A system prompt as in official code for Mini-GPT4 is set up.

However, in the original paper, I notice that there are huge gaps of performance in reference of Figure 2. The score of perception is 866.58 and that of cognition is 292.14, ranking the first place. 

I wonder where does this difference come from and which one should be taken as correct evaluation.

**Comment by BradyFU** [comment]
Thanks for your attention. The difference comes from the prompt accumulation: the status of the previous question and answer is not cleared when a new question is asked. The results in the official leaderboards are latest.

**Comment by zycheiheihei** [comment]
Can you release the prompt template for different models during evaluation? I am trying hard to reproduce the results for InstructBlip, but it seems there could be some variance due to diverse prompts.

**Comment by BradyFU** [comment]
Would you mind leaving your WeChat ID? We can communicate further through WeChat.
