### ISSUE TITLE
Image download error

### ISSUE THREAD

**Issue by John-Ge** [BradyFU/Awesome-Multimodal-Large-Language-Models#51]
I found that 03d5e3bfc958be38.jpg could not be downloaded. Could you fixed the link or upload the image? the link is:
https://upload.wikimedia.org/wikipedia/commons/a/a2/Pietrarsa_railway_museum_67.JPG

**Comment by BradyFU** [comment]
Thanks. You can find from the readme file in the folder of landmark/images:

# On June 29, 2023, we find that the link of "03d5e3bfc958be38.jpg" may no longer work, you may consider downloading it from the link below as a replacement, following its license:

Link: https://www.wikidata.org/wiki/Q310249#/media/File:Museo_nazionale_ferroviario_di_Pietrarsa_-_locomotiva_899.006.jpg
