### ISSUE TITLE
I can not find Octopus.

### ISSUE THREAD

**Issue by txdtplus** [BradyFU/Awesome-Multimodal-Large-Language-Models#59]
The method Octopus can not be found.
![image](https://github.com/BradyFU/Awesome-Multimodal-Large-Language-Models/assets/47321866/f8b1c8f2-5c5e-4817-9163-d0d7dd15b915)

**Comment by BradyFU** [comment]
Thanks for your reminder. I am contacting the author.

**Comment by BradyFU** [comment]
The new demo of Octopus: https://17b56cb5aa22eb65bf.gradio.live/

**Comment by BradyFU** [comment]
The paper is still in preparing. You could leave your WeChat ID and I will introduce the author of Octopus for you.

**Comment by txdtplus** [comment]
> The paper is still in preparing. You could leave your WeChat ID and I will introduce the author of Octopus for you.

Thank you for your help. We hope the paper will be published soon!
