### ISSUE TITLE
Github link to the multiInstruct paper

### ISSUE THREAD

**Issue by zhiyangxu-VT** [BradyFU/Awesome-Multimodal-Large-Language-Models#7]
Thanks for organizing such useful repo for multimodal papers. I am the author of the multiInstruct paper. We recently open sourced all the datasets and instructions used in our multimodal Instruction tuning paper: MultiInstruct: Improving Multi-Modal Zero-Shot Learning via Instruction Tuning. After submission, we explain the number of tasks to 62. 
Here is the GitHub link: https://github.com/VT-NLP/MultiInstruct

Could please help me to update the GitHub link in your repo?

BTW, we plan to release additional 150 diverse vision-language tasks next month.

**Comment by xjtupanda** [comment]
Thanks for your reminder! The corresponding item has been updated.
