### ISSUE TITLE
New Llava 1.5 and Mini GPT-v2 on Leaerboard?

### ISSUE THREAD

**Issue by chigkim** [BradyFU/Awesome-Multimodal-Large-Language-Models#74]
Hi,

[Llava 1.5](https://llava.hliu.cc/) and [MiniGPT-v2](https://minigpt-v2.github.io/) are released recently.
Does the [Leaderboard](https://github.com/BradyFU/Awesome-Multimodal-Large-Language-Models/tree/Evaluation) reflect the latest updates?

Thanks,

**Comment by BradyFU** [comment]
Thanks. I am trying to contact the authors to display their own results.

**Comment by chigkim** [comment]
Also Huggingface released a multimodal model, called Idefics (9B and 80B).

https://huggingface.co/spaces/HuggingFaceM4/idefics_playground
