### ISSUE TITLE
[An simple question] The visualization of Evaluation Results.

### ISSUE THREAD

**Issue by ifshine** [BradyFU/Awesome-Multimodal-Large-Language-Models#81]
I want to learn how to Creating a Python Radar Chart like [yours](https://github.com/BradyFU/Awesome-Multimodal-Large-Language-Models/blob/Evaluation/images/evaluation-1029.png).

I wonder whether you could share the code. Thanks!

**Comment by BradyFU** [comment]
Hi! You can try to contact Xu Lin: https://github.com/isLinXu
