### ISSUE TITLE
What is the difference between main and evaluation branch?

### ISSUE THREAD

**Issue by zhimin-z** [BradyFU/Awesome-Multimodal-Large-Language-Models#83]
I feel confused about those two branches since it seems the evaluation branch is out of sync with the main branch...
Anyone could confirm which branch I should refer to if I want to commit?

**Comment by BradyFU** [comment]
Hello Zhimin, many thanks for your attention on our works. The main branch keeps up to date with the latest MLLM papers, while the evaluation branch focuses on our MME leaderboards.
