### ISSUE TITLE
Wrong table under perception track

### ISSUE THREAD

**Issue by xiaoachen98** [BradyFU/Awesome-Multimodal-Large-Language-Models#84]
Nice work! However, I want to kindly remind that the table under perception track seems to be cognition.

**Comment by xiaoachen98** [comment]
By the way, our ShareGPT4V demo is available now at https://huggingface.co/spaces/Lin-Chen/ShareGPT4V-7B. Many thanks!

**Comment by BradyFU** [comment]
Many thanks for your reminder and support! The leadboards have been fixed and the demo of your great work ShareGPT4V has been added. Thank you again! : )
