### ISSUE TITLE
How to convert the MLLM response to Y/N labels?

### ISSUE THREAD

**Issue by llyx97** [BradyFU/Awesome-Multimodal-Large-Language-Models#86]
Hi, 
Thanks for sharing the great work!
I have a question regarding the conversion of MLLM's responses into Y/N labels. Could you please provide more details on how this conversion process is implemented in MME?

**Comment by BradyFU** [comment]
Thanks for your attention on our work. We use the instruction of "Please answer yes or no."

**Comment by llyx97** [comment]
Thanks for the response. 

However, the MLLMs may not strictly follow the instructions to answer "yes" or "no". For example, the MLLM may respond "The photo is taken inside a greenhouse, ..." (taken from Fig.4 in the MME paper). Could you explain more on how to convert such responses into Y/N labels?

Best regards,

**Comment by BradyFU** [comment]
In such a case,  the model can not follow the simple instruction, and thus we judge the model delivers a wrong answer. Thank you.

**Comment by llyx97** [comment]
Got it. Many thanks.
