### ISSUE TITLE
Integration Request: 'Honeybee: Locality-enhanced Projector for Multimodal LLM' 

### ISSUE THREAD

**Issue by khanrc** [BradyFU/Awesome-Multimodal-Large-Language-Models#95]
Hello,

Thank you for this great project!

Could you add our recent work, "Honeybee: Locality-enhanced Projector for Multimodal LLM"?
We used MME as an evaluation benchmark in this work, thanks! :)

- paper: https://arxiv.org/abs/2312.06742
- code: https://github.com/kakaobrain/honeybee

**Comment by xjtupanda** [comment]
Thanks for sharing! We have added the paper to our repo.
Please also consider citing our survey paper, which tracks the frontier of MLLMs:
```
@article{yin2023survey,
  title={A Survey on Multimodal Large Language Models},
  author={Yin, Shukang and Fu, Chaoyou and Zhao, Sirui and Li, Ke and Sun, Xing and Xu, Tong and Chen, Enhong},
  journal={arXiv preprint arXiv:2306.13549},
  year={2023}
}
```

**Comment by khanrc** [comment]
Thanks!
