### ISSUE TITLE
Request for Data Access

### ISSUE THREAD

**Issue by chancharikmitra** [BradyFU/Awesome-Multimodal-Large-Language-Models#97]
Hello! 

I've reached out a couple of times to the guilinli@stu.xmu.edu.cn email that was listed in the directions to get access to your dataset. We appreciate your contribution, and we would like to evaluate our method on your benchmark. If you could please check the email request we sent, that would be greatly appreciated.

Best,
Chancharik

**Comment by BradyFU** [comment]
Hi Chancharik,

Many thanks for your attention on our work. Could you provide your email address? I am contacting the data administrator to tackle the problem. Please wait a moment.

Best regard,
Chaoyou

**Comment by BradyFU** [comment]
Hi Chancharik,

The data administrator has checked the email and found that he has replied to you twice. So you could check your email. Please feel free to contact me if you have any questions.

**Comment by chancharikmitra** [comment]
Apologies, seems it was caught in our spam folder. Thank you for clarifying!

**Comment by BradyFU** [comment]
You are welcome!
