### ISSUE TITLE
Related works

### ISSUE THREAD

**Issue by MSheng-Lee** [BradyFU/Awesome-Multimodal-Large-Language-Models#99]
Hello,

Thanks for the great project. We have a new paper related to multimodal 3D instruction-following dataset and benchmark. Would you consider adding our recent work into the project?

Project Page: https://m3dbench.github.io/

Github: https://github.com/OpenM3D/M3DBench

Arxiv Link: https://arxiv.org/abs/2312.10763

Thanks a lot.

**Comment by xjtupanda** [comment]
Thanks for sharing! We have added the paper to our repo.
If you find our projects helpful to your research, please consider citing:
```
@article{yin2023survey,
  title={A Survey on Multimodal Large Language Models},
  author={Yin, Shukang and Fu, Chaoyou and Zhao, Sirui and Li, Ke and Sun, Xing and Xu, Tong and Chen, Enhong},
  journal={arXiv preprint arXiv:2306.13549},
  year={2023}
}

@article{fu2023mme,
  title={MME: A Comprehensive Evaluation Benchmark for Multimodal Large Language Models},
  author={Fu, Chaoyou and Chen, Peixian and Shen, Yunhang and Qin, Yulei and Zhang, Mengdan and Lin, Xu and Qiu, Zhenyu and Lin, Wei and Yang, Jinrui and Zheng, Xiawu and Li, Ke and Sun, Xing and Ji, Rongrong},
  journal={arXiv preprint arXiv:2306.13394},
  year={2023}
}
```

**Comment by MSheng-Lee** [comment]
> Thanks for sharing! We have added the paper to our repo. If you find our projects helpful to your research, please consider citing:
> 
> ```
> @article{yin2023survey,
>   title={A Survey on Multimodal Large Language Models},
>   author={Yin, Shukang and Fu, Chaoyou and Zhao, Sirui and Li, Ke and Sun, Xing and Xu, Tong and Chen, Enhong},
>   journal={arXiv preprint arXiv:2306.13549},
>   year={2023}
> }
> 
> @article{fu2023mme,
>   title={MME: A Comprehensive Evaluation Benchmark for Multimodal Large Language Models},
>   author={Fu, Chaoyou and Chen, Peixian and Shen, Yunhang and Qin, Yulei and Zhang, Mengdan and Lin, Xu and Qiu, Zhenyu and Lin, Wei and Yang, Jinrui and Zheng, Xiawu and Li, Ke and Sun, Xing and Ji, Rongrong},
>   journal={arXiv preprint arXiv:2306.13394},
>   year={2023}
> }
> ```

Thanks a lot. We will add these wonderful works in our later version.
